# Generated by Django 4.2.7 on 2024-05-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0001_initial'),
    ]   

    operations = [
        migrations.RenameField(
            model_name='contactformsubmision',
            old_name='full_name',
            new_name='name',
        ),
    ]
