# Generated by Django 4.2.7 on 2024-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0013_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='Wallet_Address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
