# Generated by Django 4.2.7 on 2024-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0015_rename_age_profile_tel_profile_bitcoin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
