# Generated by Django 4.2.7 on 2024-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0016_profile_bonus_profile_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
