# Generated by Django 4.2.7 on 2024-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0017_profile_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
