# Generated by Django 4.2.7 on 2024-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0018_alter_profile_bonus_alter_profile_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Select_Balance_Type',
            field=models.CharField(choices=[('Total balance', 'Total balance')], max_length=50),
        ),
    ]
