# Generated by Django 4.2.7 on 2024-05-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0019_alter_transactions_select_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=-100),
        ),
    ]
