# Generated by Django 4.2.7 on 2024-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0020_alter_profile_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=100),
        ),
    ]
