# Generated by Django 4.2.7 on 2024-07-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0022_transactions_user_alter_profile_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Select_Balance_Type',
            field=models.CharField(choices=[('Profit', 'Profit <django.db.models.query_utils.DeferredAttribute object at 0x0000021A326F9250>'), ('Bonus', 'Bonus <django.db.models.query_utils.DeferredAttribute object at 0x0000021A326F9220>')], max_length=50),
        ),
    ]
