# Generated by Django 4.2.7 on 2024-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0023_alter_transactions_select_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Select_Balance_Type',
            field=models.CharField(choices=[('Total balance', 'Total balance')], max_length=50),
        ),
    ]
