# Generated by Django 4.2.7 on 2024-07-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0024_alter_transactions_select_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Select_Balance_Type',
            field=models.CharField(choices=[('Profit', 'Profit')], max_length=50),
        ),
    ]
